"""add calendar_subscriptions table

Revision ID: c3d4e5f6a7b8
Revises: a1b2c3d4e5f6
Create Date: 2026-04-04 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3d4e5f6a7b8'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('color', sa.String(length=32), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('cache_ttl_minutes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_refresh_at', sa.DateTime(), nullable=True),
    sa.Column('last_refresh_status', sa.String(length=64), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('calendar_subscriptions', schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f('ix_calendar_subscriptions_user_id'),
            ['user_id'],
            unique=False,
        )
    # ### end Alembic commands ###


def downgrade():
    # ### end Alembic commands ###
    with op.batch_alter_table('calendar_subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_calendar_subscriptions_user_id'))

    op.drop_table('calendar_subscriptions')
    # ### end Alembic commands ###
